# Generated by Django 2.2.1 on 2019-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Obligatorio', max_length=50)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='')),
            ],
        ),
    ]
