# Generated by Django 2.2.6 on 2019-11-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_auto_20191111_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='asesoria/apps/novedades'),
        ),
    ]
