# Generated by Django 2.2.1 on 2019-10-16 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(help_text='Ingrese el código.', unique=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Código')),
                ('nombre', models.CharField(help_text='Ingrese el nombre.', max_length=40)),
                ('hora_1_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la primera hora.', null=True, verbose_name='Desde')),
                ('hora_1_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la primera hora.', null=True, verbose_name='Hasta')),
                ('hora_2_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la segunda hora.', null=True, verbose_name='Desde')),
                ('hora_2_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la segunda hora.', null=True, verbose_name='Hasta')),
                ('hora_3_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la tercer hora.', null=True, verbose_name='Desde')),
                ('hora_3_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la tercer hora.', null=True, verbose_name='Hasta')),
                ('hora_4_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la cuarta hora.', null=True, verbose_name='Desde')),
                ('hora_4_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la cuarta hora.', null=True, verbose_name='Hasta')),
                ('hora_5_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la quinta hora.', null=True, verbose_name='Desde')),
                ('hora_5_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la quinta hora.', null=True, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
